
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY *.sln .
COPY ChatApp.API/*.csproj ./ChatApp.API/
COPY ChatApp.Application/*.csproj ./ChatApp.Application/
COPY ChatApp.Domain/*.csproj ./ChatApp.Domain/
COPY ChatApp.Infrastructure/*.csproj ./ChatApp.Infrastructure/
COPY Tests/*.csproj ./Tests/


RUN dotnet restore


COPY . .


RUN dotnet build -c Release -o /out


FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .


EXPOSE 8080
ENTRYPOINT ["dotnet", "ChatApp.API.dll"]
